import type { IconOption } from '@/types/workflow'

export const AVAILABLE_ICONS: IconOption[] = [
  { name: 'Flask', class: 'fas fa-flask' },
  { name: 'Vial', class: 'fas fa-vial' },
  { name: 'Atom', class: 'fas fa-atom' },
  { name: 'Test Tube', class: 'fas fa-test-tube' },
  { name: 'Fire', class: 'fas fa-fire' },
  { name: 'Snowflake', class: 'fas fa-snowflake' },
  { name: 'Lightning', class: 'fas fa-bolt' },
  { name: 'Magnet', class: 'fas fa-magnet' },
  { name: 'Radiation', class: 'fas fa-radiation' },
  { name: 'Biohazard', class: 'fas fa-biohazard' },
  { name: 'Virus', class: 'fas fa-virus' },
  { name: 'DNA', class: 'fas fa-dna' },
  { name: 'Prescription', class: 'fas fa-prescription' },
  { name: 'Pills', class: 'fas fa-pills' },
  { name: 'Capsules', class: 'fas fa-capsules' },
  { name: 'Syringe', class: 'fas fa-syringe' },
  { name: 'Heartbeat', class: 'fas fa-heartbeat' },
  { name: 'Stethoscope', class: 'fas fa-stethoscope' },
  { name: 'X-Ray', class: 'fas fa-x-ray' },
  { name: 'Microscope', class: 'fas fa-microscope' },
  { name: 'Funnel', class: 'fas fa-filter' },
  { name: 'Hourglass', class: 'fas fa-hourglass-half' },
  { name: 'Thermometer', class: 'fas fa-thermometer-half' },
  { name: 'Scale', class: 'fas fa-weight' },
  { name: 'Droplet', class: 'fas fa-tint' },
  { name: 'Sun', class: 'fas fa-sun' },
  { name: 'Moon', class: 'fas fa-moon' },
  { name: 'Star', class: 'fas fa-star' },
  { name: 'Cog', class: 'fas fa-cog' },
  { name: 'Tools', class: 'fas fa-tools' }
]